### PR TITLE
adding q3 payment methods for Altpay

### PR DESCRIPTION
**Pull request by aditya27marri**

### CODE REVIEW

**Comment by bluepnume** [comment]
This PR only seems to change the flow types. Assuming you also need to change the gql request?

**Comment by aditya27marri** [comment]
Fixed it. Please check now

**Comment by bluepnume** [comment]
I still see the `:` characters in the gql query

**Comment by aditya27marri** [comment]
Really sorry for the trouble. Please check now

**Comment by bluepnume** [comment]
Looks good! Is this ready to be merged now, or do GQL changes still need to be released?

**Comment by aditya27marri** [comment]
I think this is good. I will fix xobuyernodeweb and will let you know

**Pull request merged**
