### PR TITLE
Card autofill

### PR DESCRIPTION
**Pull request by crookedneighbor**
### Description

This should (theoretically) add support for browser autofill of credit cards. It's not easy to test right now, because for it to work, both the parent page and the iframes need to be on https with valid certs.

### Why are we making these changes? Include references to any related Jira tasks or GitHub Issues

A customer should be able to autofill their credit card when using the single card fields.

Jira: DTNOR-238

### Reproduction Steps (if applicable)

Start typing in a card number you have saved in your browser. In Safari, the number will pop up, but the other fields won't populate. In Chrome, nothing happens.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I think this one should be good to go, once it can get reviewed. Again, we can't really test this until we can put it in an https environment with valid certs.

**Review by wsbrunson — APPROVED** [review]

**Comment by crookedneighbor** [comment]
Are we waiting on anything for this? or is it ready to be merged?

**Review by wsbrunson — APPROVED** [review]

**Comment by crookedneighbor** [comment]
Brought this up to date.

**Comment by crookedneighbor** [comment]
Can we turn off codecov duplication detection for the test directory? Test code naturally has a lot of duplication, so not sure why we care about DRYing it out. Maybe I'm just misunderstanding though.

If this is good to go, could someone with merge access merge it?

**Review by westeezy — APPROVED** [review]

**Comment by westeezy** [comment]
we can take a look at our codecov settings. as well. I'll make a task for that to do it separately

**Pull request merged**
