### PR TITLE
venmo wallet support added

### PR DESCRIPTION
**Pull request by gabrielo91**
## Description

- Similar to the "Pay Now" button for returning Pay Later users, we need to create a button for returning Venmo Pay buyers that have Venmo branding and has the buyer's Venmo username in there.
- [This PR](https://github.com/paypal/paypal-checkout-components/pull/1647) in `paypal-checkout-components` contains the visual changes required in order to show the required label

- And [this one](https://github.paypal.com/Checkout-R/xobuyernodeserv/pull/2152) in `xobuyernodeserv` retrieves such data from the API

### How it was tested:

- Till now I couldn't render the right button using the demo, however,  I got the graphQL query built, which I leave below

```graphql
query GetSmartWallet(
  $clientID: String!
  $merchantID: [String!]
  $currency: String
  $amount: String
  $userIDToken: String
  $userRefreshToken: String
  $userAccessToken: String
  $vetted: Boolean
  $paymentMethodNonce: String
  $branded: Boolean
) {
  smartWallet(
    clientId: $clientID
    merchantId: $merchantID
    currency: $currency
    amount: $amount
    userIdToken: $userIDToken
    userRefreshToken: $userRefreshToken
    userAccessToken: $userAccessToken
    vetted: $vetted
    paymentMethodNonce: $paymentMethodNonce
    branded: $branded
  ) {
    paypal {
      instruments {
        type
        label
        logoUrl
        instrumentID
        tokenID
        vendor
        oneClick
        branded
      }
    }
    credit {
      instruments {
        type
        label
        logoUrl
        instrumentID
        tokenID
        vendor
        oneClick
        branded
      }
    }
    card {
      instruments {
        type
        label
        logoUrl
        instrumentID
        tokenID
        vendor
        oneClick
        branded
      }
    }
    venmo {
      instruments {
        type
        label
        logoUrl
        instrumentID
        tokenID
        vendor
        oneClick
        branded
      }
    }
  }
}
```

### Query Variables

```json
{"clientID":"alc_client1","buyerCountry":"US","currency":"USD","commit":true,"vault":false,"intent":"CAPTURE","disableFunding":[],"enableFunding":["VENMO"],"disableCard":[]}
```

### HTTP Headers
```json
{"x-paypal-security-context":"{\"actor\":{\"user_type\":\"API_CALLER\",\"auth_state\":\"LOGGEDIN\",\"auth_claims\":[\"CLIENT_ID_SECRET\"],\"legal_country\":\"\",\"tenant_context\":{\"tenant_name\":\"VENMO\",\"tenant_id\":\"65B786CC-E0BB-4B20-AC72-C69FF1A65CE2\"},\"client_id\":\"internalMidtierApplication\"},\"subjects\":[{\"subject\":{\"public_credential\":\"_sys_aquarium-8413030933804880@paypal.com\",\"id\":\"406232506\",\"auth_claims\":[\"USERNAME\",\"PASSWORD\"],\"auth_state\":\"LOGGEDIN\",\"account_number\":\"4776338151588252626\",\"encrypted_account_number\":\"UKZBFRJJH7YGQ\",\"party_id\":\"4776338151588252626\",\"authenticating_user\":true,\"user_type\":\"CONSUMER\",\"tenant_context\":{\"tenant_name\":\"VENMO\",\"tenant_id\":\"65B786CC-E0BB-4B20-AC72-C69FF1A65CE2\"},\"identity_provider\":\"urn:idp:paypal\",\"legal_country\":\"US\"},\"features\":[]}],\"auth_token\":\"A005Jop8NwjRCgjTevB6zgwHdkhiKnEFvuAvySDQC9JmYAw\",\"auth_token_type\":\"ACCESS_TOKEN\",\"scopes\":[\"https://api.paypal.com/v1/payments/.*\",\"https://uri.paypal.com/services/identity/proxyclient\",\"https://uri.paypal.com/services/initialize-upstream-presentment\",\"openid\"],\"global_session_id\":\"Ie23c8c86-c24e-4499-b573-e6af26f0c604\",\"last_validated\":1623267077.48,\"version\":\"1.2\",\"claims\":{\"subject_payer_id\":\"UKZBFRJJH7YGQ\",\"internal_application\":\"true\",\"consent_id\":\"CQQ34gUdNnhM9J2gGKt_0m4VpdZpM150x5HjzYG-eJs\"},\"signature\":\"eyJraWQiOiJhdXRoX3NlY3VyaXR5X2NvbnRleHRfc2lnbl9rZXkiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOiIxNjIzMjY3MDc3IiwiZXhwIjoiMTYyMzI5NTg3NyIsInNoYTI1Nl9kaWdlc3QiOiI3Yk5iTXZkdXJFVXFOQ3VoeGttb1E2dUNiXy1LdFdGV1VTS2thVkx5WklBIn0.l9S5YnTXE3wr3OnxnFLWO_g1JsBdYYdYX8gdkz2GiZGAQ3kuw9M6xIGrsdnVXViCFC9Usfidg6GQWWz6a3yk5xEloSwqY2erk-UdoQTVWI4o0TJia3d9lllv5UCBRaErKhHhVKBwXiRaz3EH152-kpQSu4KL9hU6SDugDHIbWlszNPfvHfSZkLCyPudX5oq2Qj6LGIgdT3gsh6gWLJa8xFdjEz06AWsrHqKynMdMOMbAa7_qUwBuFZZVOIudlX__6GnONE8FTwiqSLdxXlJBchYIWD9z8UyDCmxd_ka27RJqXXjxl6TH92PUaz_lhwq5UiwWWJW1l_eZXZ9jbB543w\",\"client_id\":\"internalMidtierApplication\",\"edge_authorization\":{\"policy_decision\":\"PERMIT\",\"obligations\":[]}}"}
```

### Result

- This generates the expected result, as shown below

```json
{
  "data": {
    "smartWallet": {
      "paypal": {
        "instruments": []
      },
      "credit": {
        "instruments": []
      },
      "card": {
        "instruments": []
      },
      "venmo": {
        "instruments": [
          {
            "type": null,
            "label": "_sys_aquarium-3604263830921715@paypal.com",
            "logoUrl": null,
            "instrumentID": null,
            "tokenID": null,
            "vendor": null,
            "oneClick": true,
            "branded": null
          }
        ]
      }
    }
  },
  "extensions": {
    "correlation_id": "db4c69f054bd1"
  }
}
```

### Related PR's
- https://github.paypal.com/Checkout-R/xobuyernodeserv/pull/2152
- https://github.com/paypal/paypal-checkout-components/pull/1647

### CODE REVIEW

**Review by mnicpt — APPROVED** [review]

**Review by bluepnume — APPROVED** [review]

**Comment by mstuart** [comment]
lgtm!

**Comment by mstuart** [comment]
@gabrielo91 I saw "_sys_aquarium-3604263830921715@paypal.com" listed as the label in the response. Are we using email for now because the Venmo username isn't available in SCIM (yet)?

**Comment by gabrielo91** [comment]
@mstuart can´t respond with confidence since I don't know what is happening under the hood, It can be due to what you set or maybe because it is a "test" user and that's the value set in that field. Even in the service documentation, the examples show the email in the username field

**Comment by mstuart** [comment]
cool! I assume it's because the username isn't populated always, so it'll default to e-mail. I think we'd run into character limits if we were to display the e-mail on the button, but we can figure that out later before turning this on :) 

I think this is good to merge 👍

**Pull request merged**
