### PR TITLE
Create badge.svg?branch=master)

### PR DESCRIPTION
**Pull request by themaximumspension**
Yup

### CODE REVIEW

**Comment by themaximumspension** [comment]
> # [Codecov](https://codecov.io/gh/paypal/paypal-smart-payment-buttons/pull/98?src=pr&el=h1) Report
> > Merging [#98](https://codecov.io/gh/paypal/paypal-smart-payment-buttons/pull/98?src=pr&el=desc) ([e2b6ca1](https://github.com/paypal/paypal-smart-payment-buttons/commit/e2b6ca18cd98add1b89981346c36b9ec2ea8ca4d)) into [master](https://codecov.io/gh/paypal/paypal-smart-payment-buttons/commit/6eb01cff242838f89bc8d11886f8ed19ed6920d9?el=desc) ([6eb01cf](https://github.com/paypal/paypal-smart-payment-buttons/commit/6eb01cff242838f89bc8d11886f8ed19ed6920d9)) will **not change** coverage.
> > The diff coverage is `n/a`.
> 
> [Impacted file tree graph](https://codecov.io/gh/paypal/paypal-smart-payment-buttons/pull/98?src=pr&el=tree)
> 
> ```diff
> @@           Coverage Diff           @@
> ##           master      #98   +/-   ##
> =======================================
>   Coverage   49.44%   49.44%           
> =======================================
>   Files          42       42           
>   Lines        1175     1175           
>   Branches      278      278           
> =======================================
>   Hits          581      581           
>   Misses        488      488           
>   Partials      106      106           
> ```
> 
> [Continue to review full report at Codecov](https://codecov.io/gh/paypal/paypal-smart-payment-buttons/pull/98?src=pr&el=continue).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/paypal/paypal-smart-payment-buttons/pull/98?src=pr&el=footer). Last update [6eb01cf...e2b6ca1](https://codecov.io/gh/paypal/paypal-smart-payment-buttons/pull/98?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by themaximumspension** [comment]
No

**Comment by gregjopa** [comment]
@themaximumspension this looks like spam. Closing.

**Review by themaximumspension — COMMENTED** [review]
gh pr checkout 98

**Review by themaximumspension — COMMENTED** [review]
Under inspection

**Pull request closed without merging**
