### PR TITLE
Pass 'enableFunding' option to graphql mobileSDKEligibility query

### PR DESCRIPTION
**Pull request by gregjopa**
Working on adding support for the enableFunding query param

### CODE REVIEW

**Review by bluepnume — APPROVED** [review]

**Review by mnicpt — APPROVED** [review]

**Review by mnicpt — APPROVED** [review]

**Comment by bluepnume** [comment]
Looks good! But if this is for venmo I think you'll also need to update native sdk eligibility call, to pass enableFunding there too

**Comment by gregjopa** [comment]
> if this is for venmo I think you'll also need to update native sdk eligibility call, to pass enableFunding there too

@bluepnume great point. This is for venmo. I'll push an update for the native sdk eligibility call.

**Comment by mstuart** [comment]
Lgtm! Does the funding eligibility stuff from earlier need to be there too? Or just the SDK eligibility part?

**Comment by mnicpt** [comment]
> Lgtm! Does the funding eligibility stuff from earlier need to be there too? Or just the SDK eligibility part?

Was wondering the same.  Will both GQL calls be expecting `enableFunding`?

**Comment by gregjopa** [comment]
> Does the funding eligibility stuff from earlier need to be there too? Or just the SDK eligibility part?

Good question. I looked up the graphql query and `fundingEligibility` does support enableFunding so it may be fine to just keep it:

Screen Shot 2021-01-20 at 4 54 18 PM

Happy to remove it as well. Let me know your thoughts.

**Comment by mstuart** [comment]
Just the mobileSDKEligibility one will 👍

**Comment by gregjopa** [comment]
I went ahead and reverted the other changes since they are not needed. I kept the mobileSDKEligibility change.

**Comment by mstuart** [comment]
lgtm!

**Comment by bluepnume** [comment]
Looks good to me! The previous changes would be good to close some tech debt if you still have them. But will merge this.

**Pull request merged**
